name: rainymotion-docs-rtd
channels:
  - conda-forge
dependencies:
  - python=3.5
  - opencv
  - numpy 
  - scipy 
  - scikit-learn 
  - scikit-image 
  - h5py 
  - matplotlib 
  - jupyter
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx

